### ISSUE TITLE
Add focus/hover effects to all charts

### ISSUE THREAD

**Issue by bnhovde** [bengler/imdikator#34]
- See barChart for implementation
- Might need tweaking for line charts (and bubble charts)

**Comment by TurboTobias** [comment]
The client doesn't have much interest in this. They had someone external do a review of the usability throughout the site and they were the ones that recommended using arrow keys instead of tab. Doesn't make much sense. Having the ability to tab through simple diagrams made sense - and the client was still interested in this. They agreed to _not_ tabbing through huge data sets like line and bubble charts.
